### ISSUE TITLE
add more templete

### ISSUE THREAD

**Issue by koalalu007** [koalalu007/resume-maker#1]

**Comment by Sanketmane2323** [comment]
I would like to work on these issue but i want know what kind of template you want add

**Comment by mohitsaini07** [comment]
Hi @koalalu007, I would like to work on this issue

**Comment by GautamTirumala** [comment]
https://codepen.io/dudleystorey/pen/NqaYxy
This looks good to me, Create a new folder with HTML and CSS page, Create a new form by the inputs in the above and integrate it

**Comment by GautamTirumala** [comment]
Hi @koalalu007 to add more templates we have to discuss #21 and organize the project.
