### ISSUE TITLE
Improve the overall UI/UX of the page.

### ISSUE THREAD

**Issue by Clou-D-Walker** [koalalu007/resume-maker#13]
I noticed it in the project and would like to work on styling the box, giving proper font colors and adding hover effect on download pdf button as hacktoberfest candidate.

**Comment by nishantshukla2884** [comment]
Hi i am interested in contributing to this issue , could you please assign it to me @Clou-D-Walker

**Comment by Sanketmane2323** [comment]
Hey @koalalu007  i would like to  work on this issue

**Comment by Sanketmane2323** [comment]
Hey @koalalu007 i have made changes in UI can u check it once

**Comment by MuskanPastor** [comment]
Hi i am interested in contributing to this issue , could you please assign it to me @Clou-D-Walker
