### ISSUE TITLE
Improve input types

### ISSUE THREAD

**Issue by Abhijit-033** [koalalu007/resume-maker#16]
It would be better to modify the input types for email and mobile number to ensure user enters correct data.
Along with that we can improve the input for date like Graduation data, Experience date to make it easier for users.

**Comment by Abhijit-033** [comment]
I am new to github so I made the pull request before issue raise.
When shall I make the pull request with updated files?

**Comment by THEFZNKHAN** [comment]
I would like to work on this issue.
Please assign me this Issue.

**Comment by Sanketmane2323** [comment]
I have changed the types of the input ...please check it once

**Comment by THEFZNKHAN** [comment]
I already made the necessary changes according to the above issue #16 in #19 PR.
please check and let me know if I need to make any further changes.
and if no further changes are required then kindly merge my PR and add the "Hacktoberfest-accepted" label

**Comment by Abhinab04** [comment]
can i work on this? @koalalu007
