### ISSUE TITLE
Add Horizontal Rule After Name and Center-Align Name

### ISSUE THREAD

**Issue by bprathamesh20** [koalalu007/resume-maker#17]
Issue Description:

**Summary:**
This issue aims to enhance the appearance of the navigation header by introducing a horizontal rule (line) after the name and center-aligning the name for improved visual presentation and alignment.

**Details:**
- Currently, the name in the navigation header lacks a clear visual separation from the rest of the content.
- To address this, we propose adding a horizontal rule (line) immediately after the name to create a visual distinction.
- Additionally, we plan to center-align the name text within the header for better aesthetics and alignment.

**Tasks:**
- Add a horizontal rule after the name.
- Center-align the name text within the header.

**Existing UI**
![image](https://github.com/koalalu007/resume-maker/assets/98270118/597ca212-695a-40d2-a7a0-e58f287c3fdd)

**Expected Outcome:**
Upon implementing these changes, the navigation header will have improved readability and a more polished appearance.
![image](https://github.com/koalalu007/resume-maker/assets/98270118/10f99c6a-9a32-4624-bcdc-4356fc7a25a7)

**Comment by Sanketmane2323** [comment]
Hey @koalalu007  I would like to work on these issue...
