### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by koalalu007** [koalalu007/resume-maker#2]

**Comment by samsara-02** [comment]
Hey,

I'm up for this issues. Do you have more details to give me ?

**Comment by tanu-chahal** [comment]
Hi @koalalu007, I tried running the project was thinking of updating readme.md 
But found out that I'm not able to download the resume, are you able to? Is this the issue only I'm facing or everyone is facing it?

**Comment by koalalu007** [comment]
> Hi @koalalu007, I tried running the project was thinking of updating readme.md But found out that I'm not able to download the resume, are you able to? Is this the issue only I'm facing or everyone is facing it?

you can solve this issue

**Comment by tvermaashutosh** [comment]
@koalalu007 
I would like to improve the readme by adding about the Hacktoberfest as this repo is open for Hacktoberfest. It would also help newbies to understand how to register for hacktoberfest and information about the same.
So please assign it to me.

**Comment by sunny7899** [comment]
hi @koalalu007  can u assign some task to me so that i can contribute.
