### ISSUE TITLE
Feature : Proper Folder Structure Needed.

### ISSUE THREAD

**Issue by GautamTirumala** [koalalu007/resume-maker#21]
As we are not using any libraries such as React.js, Every new template will have its own HTML, CSS and JS files, And also it will have a unique URL. To address this we should have a ***discussion*** on how the folder structure should look like.

I suggest the below structure : 

├── index.html
├── index.css
├── index.js

 ### This index files will contain pictures of templates, from which user can select which template he/she.

├── Readme.md

## All the templates should be separated in a different folder. 
├── Templates
│   ├── Template-1
│   │   ├── template-1.html
│   │   ├── template-1.css
│   │   ├── template-1.js

│   ├── Template-2
│   │   ├── template-2.html
│   │   ├── template-2.css
│   │   ├── template-2.js
.
.
.
.
....

**Comment by GautamTirumala** [comment]
@tanu-chahal currently I am not working on this, I want to first discuss with the maintainers and then come up with solution.

**Comment by koalalu007** [comment]
@GautamTirumala you can do this , make another branch for this!

**Comment by GautamTirumala** [comment]
I have started working on this.
