### ISSUE TITLE
add code of conduct.md

### ISSUE THREAD

**Issue by koalalu007** [koalalu007/resume-maker#27]
code of conduct

**Comment by Pariharx7** [comment]
I want to work on this issue. 
Can you assign me this issue.

**Comment by ashfaque-mustaque** [comment]
bro your resume is getting download even information is not filled which is drawback on which I wanna to work and also want to contribute on the styling of the downloaded resume .
@koalalu007 assign me this issue to me

**Comment by ashfaque-mustaque** [comment]
issue resolved 

![ResumeMakerProject](https://github.com/koalalu007/resume-maker/assets/106698498/ffbff014-6f39-4d6d-a1c0-1330eeefb025)

**Comment by ashfaque-mustaque** [comment]
bro merge my PR  i did it

**Comment by Pariyul** [comment]
Hello Sir ,I want to work on this issue.
Can you assign me this issue.
