### ISSUE TITLE
Want to change the UI and design

### ISSUE THREAD

**Issue by Mudasir7-Prof-Snape** [koalalu007/resume-maker#29]

**Comment by Mudasir7-Prof-Snape** [comment]
before changes
![Screenshot (66)](https://github.com/koalalu007/resume-maker/assets/140256749/1b9bd659-c40d-4788-a607-ec7fa6edb760)

**Comment by Mudasir7-Prof-Snape** [comment]
after changes
![Screenshot (67)](https://github.com/koalalu007/resume-maker/assets/140256749/4bc684f2-4030-448f-a1b7-d6442e1601e2)

**Comment by Mudasir7-Prof-Snape** [comment]
I made a PR of these changes verify it once

**Comment by Mudasir7-Prof-Snape** [comment]
please assign me

**Comment by shubhampr07** [comment]
hello, assign this to me.

**Comment by Mudasir7-Prof-Snape** [comment]
@koalalu007 these changes are in PR #31 accept it sir
