### ISSUE TITLE
Issue on clicking the download pdf

### ISSUE THREAD

**Issue by strange98350** [koalalu007/resume-maker#33]
Description: Creates empty pdf when no information is filled. 

https://github.com/koalalu007/resume-maker/assets/84301897/b5141a59-4e50-4b72-8c3c-dcbdc4297e71

**Comment by strange98350** [comment]
please assign me on this issue @koalalu007 #33

**Comment by tanu-chahal** [comment]
@strange98350 are you working on this?

**Comment by strange98350** [comment]
if the owner assigned me this issue then i will work on this problem

**Comment by Mannxxx** [comment]
I want to contribute in this @koalalu007 @strange98350

**Comment by Abhinab04** [comment]
can i contribute on this? @koalalu007

**Comment by koalalu007** [comment]
@Mannxxx @Abhinab04 done already
