### ISSUE TITLE
Improve Mobile Responsiveness: Ensure Proper Display and Functionality on Small Screens

### ISSUE THREAD

**Issue by tanu-chahal** [koalalu007/resume-maker#36]
https://github.com/koalalu007/resume-maker/assets/117712672/2da8c6d7-8c6a-4d2b-82e2-2b7e3f3658da

The site is not responsive for small screens, especially mobile phones. We need that.

**Comment by rishi-harti768** [comment]
@koalalu007 Can you please assign to this issue to me, I have lots of experience in terms of responsiveness. I have good grip in front-end.
thank you
