### ISSUE TITLE
Add CONTRIBUTING.md, ISSUE_TEMPLATE.md and PR_TEMPLATE.md

### ISSUE THREAD

**Issue by tanu-chahal** [koalalu007/resume-maker#43]
### Description

We need a .github folder, to have organized & consistent changes in the codebase, for this, we can add 3 files:

CONRIBUTING.md - the file that will contain the format to name local branches, commit messages, and PR Titles. 

ISSUE_TEMPLATE.md - A file that'll contain the template for raising an issue, like different sections Description, Current Behavior, Expected Behavior, Steps to Reproduces, Images or Video attachment displaying the bug, etc. 

PR_TEMPLATE.md - A file for the format of PR containing all important sections which issues it fixes, what changes are made, Video/Screenshots of changes, etc.

**Comment by mdyousufniaz** [comment]
I would like to create on this task, can u assign me ?
