### ISSUE TITLE
Image not showing in resume PDF.

### ISSUE THREAD

**Issue by meet244** [koalalu007/resume-maker#47]
When we select an image and then download the PDF the image is not visible in PDF.
![image](https://github.com/user-attachments/assets/d60403a8-cb92-48e9-b49f-8b7a2cd1b9e7)
![image](https://github.com/user-attachments/assets/4d90db4d-b6d7-4e14-8fa4-add4a1c1bf0a)

I can help to fix this issue, please assign this to me and also add the 'hacktoberfest' label to this issue.

**Comment by koalalu007** [comment]
working on this
