### ISSUE TITLE
Feature Request: Enhance Resume Template Maker

### ISSUE THREAD

**Issue by Singhal1808** [koalalu007/resume-maker#50]
I would like to propose a series of enhancements to the Resume Template Maker to improve its functionality and user experience.

-> Profile Image Preview: Allow users to see a preview of the uploaded profile image before downloading the resume.

-> Form Validation: Implement validation to ensure all required fields are filled correctly before downloading the PDF.

-> Download Options: Provide different formats for downloading (e.g., PDF, DOCX, or HTML). We can use libraries like jsPDF or FileSaver.js to facilitate this.

**Comment by vaibhav1724** [comment]
hi @Singhal1808, can you please assign me this issue?
