### ISSUE TITLE
Resume Not Getting Downloaded

### ISSUE THREAD

**Issue by tanu-chahal** [koalalu007/resume-maker#6]
When you enter your details on the webpage resume & click the Download PDF button. The resume doesn't get downloaded.

 I have resolved the issue, can to add the label Hacktoberfest to it & assign it to me?

**Comment by mohitsaini07** [comment]
Hi, I would like to work on this issue.

**Comment by tanu-chahal** [comment]
@koalalu007 we can close this issue as it has been resloved.
